config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'application#index'

  resources :bags do
  	resources :items do
      get 'shampoo', on: :new
      get 'new_select', on: :new
    end
  end

  resources :bags

  resources :items do
  	get 'toggle_status', :on => :member
  end

  resources :bags do
    get 'weekend', on: :new
		get 'beach', on: :new
		get 'ski', on: :new
		get 'conference', on: :new
    get 'city', on: :new
    get 'reset', :on => :member
    get 'duplicate', :on => :member
	end

end

app/models/bag.rb
class Bag < ActiveRecord::Base
	belongs_to :user
	has_many :items, dependent: :destroy

  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 40 }

  TEMPLATES = { 
  							weekend: { 
  								name: "weekend trip", 
  								items: { "socks" => 3, "pants" => 1, "shirts" => 2, "sleeping bag" => 1, "umbrella" => 1}
  							},
  							beach: {
  								name: "Beach trip", 
  								items: { "swimsuit" => 1, "towel" => 1, "flipflops" => 1, "sunblock" => 1, "book" => 1}
  							},
  							ski: {
  								name: "Ski trip",
  								items: { "ski" => 1, "ski suit" => 1, "sunglasses" => 1, "sunblock" => 1, "helmet" => 1}
								},
								conference: {
									name: "Conference", 
									items: { "laptop" => 1, "laptop charger" => 1, "sticker" => 10, "USB stick" => 2, "Club Mate" => 4}
								},
								city: {
									name: "City", 
									items: { "laptop" => 1, "laptop charger" => 1, "suit" => 1, "opera tickets" => 2, "champagne" => 1}
								} 
							}

  def duplicate_items
  	self.items.map do |item| 
			item.dup
		end
	end

	def standard_items(items)
		items.each do |name, quantity|
			item = self.items.build(name: name, quantity: quantity, bag_id: self.id)
		end
	end

	def duplicate 
		new_bag = self.dup
		new_bag.items = self.duplicate_items
		return new_bag
	end

	def standard_bags(template, user)
		bag = user.bags.build(name: template[:name])
		bag_items = template[:items]
		bag_items.each do |name, quantity|
			@item = bag.items.build(name: name, quantity: quantity, bag_id: bag.id)
		end 
		return bag
  end 

  def reset 
  	self.items.each do |item|
			item.update_attributes(status: false)	
		end
	end 

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :bag
  validates :name, presence: true, length: { maximum: 40 }
  validates :quantity, presence: true, :numericality => { :greater_than => 0, :less_than_or_equal_to => 50 }

  after_initialize :defaults

  TOILETRY = [ "shampoo", "soap", "brush", "toothbrush", "toothpaste", "bodywash", "perfume" ]
  CLOTHES = [ "socks", "underwear", "pants", "dress", "shirt", "suit", "coat", "scarf", "hat" ]
  EQUIPMENT = [ "umbrella", "travel guide", "plane ticket", "train ticket", "hotel reservation" ]
  GADGETS = [ "laptop", "laptop charger", "USB key", "phone charger", "camera", "camera charger", "camera battery" ]
  ENTERTAINMENT = [ "ebook", "book", "magazine", "handheld console" ]

  def defaults
    self.status = false if self.status.nil?
  end

  def standard_item(template, bag)
  	item = bag.items.build(name: template, quantity: "1", bag_id: bag_id)
  	return item
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bags, dependent: :destroy
  has_many :items, through: :bags, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
  	render 'layouts/home'
  end

  

  private

    # Confirms a logged-in user.
    def logged_in_user
      unless user_signed_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to new_user_session_path
      end
    end

end

app/controllers/bags_controller.rb
class BagsController < ApplicationController
	before_action :logged_in_user

	def new
    if params[:template]
      @bag = Bag.new.standard_bags(Bag::TEMPLATES[params[:template].to_sym], current_user)
      if @bag.save
      	redirect_to @bag
      else
      	flash[:danger] = "something went wrong"
      	redirect_to root_url
      end
    else
      @bag = Bag.new
    end
  end 

	def show
		@bag = Bag.find(params[:id])
	end

	def create
		@bag = current_user.bags.build(bag_params)
		if @bag.save
			flash[:success] = "Bag created!"
			redirect_to @bag
		else
			render 'new'
		end
	end

	def edit
		@bag = Bag.find(params[:id])
	end

	def update
		@bag = Bag.find(params[:id])		
		if @bag.update_attributes(bag_params)
      if URI(request.referer).path == edit_bag_path(@bag)
      	redirect_to @bag 
      else 
      	redirect_to root_url
      end
    else
    	render 'edit'
    end
	end

	def destroy
   	Bag.find(params[:id]).destroy
	  flash[:success] = "Bag deleted!"
	  redirect_to root_url
	end

	def duplicate
		@bag = Bag.find(params[:id])		
		new_bag = @bag.duplicate
		if new_bag.save
			flash[:success] = "Bag duplicated!"
			redirect_to root_url
		else
			flash[:danger] = "something went wrong"
			redirect_to root_url
		end
	end

	def reset 
		@bag = Bag.find(params[:id])
		@bag.reset
		if @bag.save
			redirect_to @bag
		else
			flash[:danger] = "something went wrong"
			redirect_to @bag
		end
	end 

	private 

		def bag_params
			params.require(:bag).permit(:name)
		end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :logged_in_user
	respond_to :html, :js

	def new
		if params[:template]
      @bag = Bag.find(params[:bag_id])	
      @item = Item.new.standard_item(params[:template], @bag)
      if @item.save
      	redirect_to @bag
      else
      	flash[:danger] = "something went wrong"
      	redirect_to @bag
      end
    else
			@item = Item.new
			@bag = Bag.find(params[:bag_id])	
		end
	end

	def create
		bag = Bag.find(params[:bag_id])
		@item = bag.items.build(item_params)
		if @item.save
			redirect_to bag
		else
			render 'new'
		end
	end

	def edit
		@item = Item.find(params[:id])
		@bag = Bag.find(params[:bag_id])
	end

	def update
		@item = Item.find(params[:id])
		@bag = Bag.find(params[:bag_id])		
		if @item.update_attributes(item_params)
			@item.update_attributes(status: false)
      redirect_to @bag
    else
    	render 'edit'
    end
	end

	def destroy
		@bag = Bag.find(params[:bag_id])
		Item.find(params[:id]).destroy
	  redirect_to @bag
	end

	def toggle_status 
		@item = Item.find(params[:id])
		@item.toggle!(:status)
		respond_to do |format|
	    format.json {render json: @item}
  	end
	end

	def shampoo
		@bag = Bag.find(params[:bag_id])
		@item = @bag.items.build(name: "Shampoo", quantity: "1", bag_id: @bag.id)
		if @item.save
			redirect_to @bag
		else
			flash[:danger] = "something went wrong"
			redirect_to @bag
		end
	end

	private 

		def item_params
			params.require(:item).permit(:name, :quantity)
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bags_helper.rb
module BagsHelper

end

app/helpers/items_helper.rb
module ItemsHelper

	def packed_link_img(to_pack)
		to_pack.status? ? 'checked.png' : 'unchecked.png'
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bags/edit.html.erb
<div class="row">
  <div class="col-md-8">
  	<h1>Rename your bag</h1>
		<%= form_for(@bag) do |f| %>
		  <%= render 'shared/error_messages', object: f.object %>
		  <div class="field">
		    <%= f.text_field :name, placeholder: "Name your bag!" %>
		  </div>
		  <%= f.submit "Save changes", class: "btn btn-primary btn-sm" %>
		<% end %>
	</div>
</div>

app/views/bags/new.html.erb
<div class="row">
  <div class="col-md-8">
  	<h1>Create a new bag!</h1>
		<%= form_for(@bag) do |f| %>
		  <%= render 'shared/error_messages', object: f.object %>
		  <div class="field">
		    <%= f.text_field :name, placeholder: "Name your bag!" %>
		  </div>
		  <%= f.submit "Post", class: "btn btn-primary btn-sm" %>
		<% end %>
	</div>
</div>

app/views/bags/show.html.erb
<div class="row">
	<div class="col-md-8">
		<h1>Your bag <span class="label label-info"><%= @bag.name %></span></h1>
		<%= link_to "change bag name", edit_bag_path(@bag), class: "btn btn-default btn-xs" %>
		<div class="items list">
			<h3>Items to pack</h3>
		  <% if @bag.items.empty? %>
		  	<p>You currently have no items in your bag...</p>
		  <% else %>
				<ul>
				  <% @bag.items.each do |item| %>
				    <li>
				    	<%= link_to image_tag(packed_link_img(item), id: "pack_img_#{item.id}"), toggle_status_item_path(item), :remote => true, class: "pack-check" %>
				    	<%= item.quantity %>
							<%= item.name %>
							<% if item.status == true %>
								<span id="packed_<%= item.id %>" class="text-primary">packed!</span>
							<% else %>
								<span id="packed_<%= item.id %>" class="text-danger">not packed</span>
							<% end %>
							<%= link_to "edit", edit_bag_item_path(@bag, item), class: "btn btn-default btn-xs" %>
							<%= link_to "delete", bag_item_path(@bag, item), method: :delete, data: { confirm: "You sure?" }, class: "btn btn-default btn-xs" %>
				    </li>
			  	<% end %>
				</ul>
			<% end %>
			<%= link_to "Add item", new_bag_item_path(@bag), class: "btn btn-primary" %>
		</div>
		<h4>Don't need this bag anymore?</h4>
		<%= link_to "Unpack all", reset_bag_path(@bag), data: { confirm: "You sure?" }, class: "btn btn-info btn-sm" %>
		<%= link_to "Delete bag", @bag, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-danger btn-sm" %>
	</div>
	<div class="col-md-4">
		<h3>Choose items</h3>
		<h4>Clothes</h4>
			<% Item::CLOTHES.each do |item| %>
				<%= link_to item, new_bag_item_path(@bag, template: item), class: "btn btn-default btn-xs" %>
			<% end %>
		<h4>Toiletry</h4>
			<% Item::TOILETRY.each do |item| %>
				<%= link_to item, new_bag_item_path(@bag, template: item), class: "btn btn-default btn-xs" %>
			<% end %>
		<h4>Equipment</h4>
			<% Item::EQUIPMENT.each do |item| %>
				<%= link_to item, new_bag_item_path(@bag, template: item), class: "btn btn-default btn-xs" %>
			<% end %>
		<h4>Gadgets</h4>
			<% Item::GADGETS.each do |item| %>
				<%= link_to item, new_bag_item_path(@bag, template: item), class: "btn btn-default btn-xs" %>
			<% end %>
		<h4>Entertainment</h4>
			<% Item::ENTERTAINMENT.each do |item| %>
				<%= link_to item, new_bag_item_path(@bag, template: item), class: "btn btn-default btn-xs" %>
			<% end %>
	</div>
</div>

app/views/items/edit.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>Edit your item</h1>

    <%= form_for [@bag, @item], url: bag_item_path, html: { method: :patch } do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <div class="field">
      	<%= f.label "How many?" %><br />
        <%= f.number_field(:quantity, in: 1..50) %>
      </div>
      
      <div class="field">
      	<%= f.label :name %><br />
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <%= f.submit "Save changes", class: "btn btn-primary btn-sm" %>
    
    <% end %>
  </div>
</div>

app/views/items/new.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>Add an item</h1>
    <%= form_for [@bag, @item], url: bag_items_path do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <p>
        <%= f.number_field(:quantity, in: 1..50, :value => 1) %>
        <%= f.text_field :name, placeholder: "What do you want to pack?", :size => 20, class: 'form-control' %>
        <%= f.submit "Add", class: "btn btn-primary btn-sm" %>
      </p>
    <% end %>
  </div>
</div>

app/views/items/new_select.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>Choose an item</h1>
    <%= form_for [@bag, @item], url: bag_items_path do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        <p>
          <%= f.number_field(:quantity, in: 1..50, :value => 1) %>
          <span id="item_select"><%= f.select :name, options_for_select(['Shampoo', 'soap', 'brush', 'toothbrush'])%></span>
          <%= f.submit "Add", class: "btn btn-primary btn-sm" %>
        </p>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <%= link_to image_tag("logo.png"), root_path, id: "logo" %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Log out', destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_user.html.erb
<div class="row">
  <div class="col-md-6">
		<h1>Welcome <%= current_user.email %></h1>
		<h3>What do you want to do?</h3>
		<h4>Create custom bag</h4>
			<%= link_to "New bag", new_bag_path, class: "btn btn-primary" %>
		<h4>Choose a standard bag</h4>
			<% Bag::TEMPLATES.each do |key, value| %>
				<%= link_to value[:name].to_s, new_bag_path(template: key), class: "btn btn-info" %>
			<% end %>
		</div>
		<div class="col-md-6">
			<div class="bags list">
				<h3>Your bags</h3>
				<% if current_user.bags.empty? %>
					<p>You don't have any bags yet.</p>
				<% else %>
					<ul>
					  <% current_user.bags.each do |bag| %>
					    <li>
					      <%= link_to bag.name, bag %>
					      <%= link_to "delete", bag, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-default btn-xs" %>
					      <%= link_to "duplicate", duplicate_bag_path(bag), class: "btn btn-default btn-xs" %>
					      <%= link_to "rename", edit_bag_path(bag), class: "btn btn-default btn-xs" %>
					    </li>
					  <% end %>
					</ul>
				<% end %>
			</div>
		</div>	
	</div>
</div>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BagItApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
    
  <div class="container">
	  <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>

	  <!--<p class="notice"><%= notice %></p>
  	<p class="alert"><%= alert %></p>-->
  	  
  	<%= yield %>

  </div>

</body>
</html>

app/views/layouts/home.html.erb
<% if user_signed_in? %>
	<%= render 'layouts/user' %>
<% else %>
	<%= render 'shared/home_default' %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
  	<div class="alert alert-danger">
  		The form contains <%= pluralize(object.errors.count, "error") %>.
  	</div>
  	<ul>
  	  <% object.errors.full_messages.each do |msg| %>
  	  <li><%= msg %></li>
  	  <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_home_default.html.erb
<div class="center jumbotron">
  
  <h1>Welcome to Bag it!</h1>
  	<h2>Bag it! helps you to pack your bags.</h2>
  	<p>You are not signed in.</p>
  
  	<%= link_to "Sign up", new_user_registration_path, class: "btn btn-lg btn-primary" %>
  	<%= link_to "Log in", new_user_session_path, class: "btn btn-lg btn-primary" %>

</div>

app/views/shared/home_default.html.erb
<div class="center jumbotron">
  
  <h1>Welcome to Bag it!</h1>
  	<h2>Bag it! helps you to pack your bags.</h2>
  	<p>You are not signed in.</p>
  
  	<%= link_to "Sign up", new_user_registration_path, class: "btn btn-lg btn-primary" %>
  	<%= link_to "Log in", new_user_session_path, class: "btn btn-lg btn-primary" %>

</div>